apiVersion: v1
kind: Service
metadata:
  name: health-insurance-portal-service
spec:
  type: NodePort
  selector:
    app: health-insurance-portal
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
